#!/usr/bin/env python3
"""
Talos Ratchet Vector Generator

This generator lives in talos-contracts (not in any SDK) to enforce the
contract-first principle. It imports canonicalization from talos_contracts.canonical
and reference implementations from the Python SDK for crypto operations.

Usage:
    python generate_vectors.py --output ../../../test_vectors/sdk/ratchet/

Requirements:
    - talos_contracts package installed (this repo)
    - talos-sdk-py installed (for reference ratchet implementation)
"""
import argparse
import hashlib
import json
import sys
from pathlib import Path

# Import ONLY from contracts (canonicalization)
try:
    from talos_contracts.canonical import canonical_json_bytes, b64u_encode, b64u_decode
except ImportError:
    print("ERROR: talos_contracts.canonical not found. Install contracts first:")
    print("  cd ../../python && pip install -e .")
    sys.exit(1)


def compute_schedule_hash(schedule_path: Path) -> str:
    """Compute schedule hash per HASHING.md specification."""
    with open(schedule_path) as f:
        schedule = json.load(f)
    
    canonical_bytes = canonical_json_bytes(schedule)
    digest = hashlib.sha256(canonical_bytes).digest()
    return b64u_encode(digest)


def generate_header_vector():
    """Generate header canonical bytes micro-vector."""
    return {
        "$schema": "http://json-schema.org/draft-07/schema#",
        "title": "Header Canonical Bytes Micro-Vector",
        "description": "Generated by talos-contracts/tools/ratchet/generate_vectors.py",
        "version": "1.1.0",
        "test_cases": []
    }


def main():
    parser = argparse.ArgumentParser(description="Generate Talos ratchet vectors")
    parser.add_argument("--output", "-o", type=Path, default=Path("../../../test_vectors/sdk/ratchet"))
    parser.add_argument("--schedule", type=Path, default=Path("../../sdk/ratchet_kdf_schedule.json"))
    args = parser.parse_args()
    
    # Compute schedule hash
    if args.schedule.exists():
        schedule_hash = compute_schedule_hash(args.schedule)
        print(f"SCHEDULE_HASH={schedule_hash}")
    else:
        print(f"WARNING: Schedule not found at {args.schedule}")
    
    print("Vector generation stub complete.")
    print("Implement full generation logic to create v1.1.0 vectors with wire_message_b64u.")


if __name__ == "__main__":
    main()
